### ISSUE TITLE
App icon

### ISSUE THREAD

**Issue by cheeaun** [zz85/space-radar-electron#1]
Requires a vibrant app icon to distinguish itself from other apps, especially when switching apps :stuck_out_tongue:

**Comment by zz85** [comment]
Thanks for the suggestion! Will have an update for that soon :)

**Comment by zz85** [comment]
![](https://pbs.twimg.com/media/CR9yTgmVEAA29fZ.jpg)

I've decided to go with the [icon on the left](https://twitter.com/BlurSpline/status/657369758854021120) for now as I feel its slightly more vibrant and reflects more of the name Space Radar. Thanks to my designer friends who contributed!

**Comment by zz85** [comment]
App icon is now shipped :) Perhaps it would be refined over future releases :smile_cat:
